### ISSUE TITLE
Getting same Tests for different test scenarios

### ISSUE THREAD

**Issue by mhettiarac** [Cornutum/tcases#133]
Hi @kerrykimbrough 

We noticed same test scenario was repeated with empty value for the petId, any reason why this happens?

![Tcases-sametestid](https://user-images.githubusercontent.com/51822287/86819721-aba3d880-c0a5-11ea-9cb6-64f29e7ec459.png)

**Comment by kerrykimbrough** [comment]
In principle, these tests are checking 4 different error conditions. But there are 2 problems here. For 3 of these conditions (empty string, null, undefined), the representation of the path param happens to be the same. And for the 4th condition (not a string value), this can't really be represented at all, since every value is serialized as string.

TFOA needs to be smarter about avoiding such duplicate tests.

**Comment by kerrykimbrough** [comment]
Fixed by PR #137
