### ISSUE TITLE
Very slow with several hundred variables and properties

### ISSUE THREAD

**Issue by AdamLeonSmith** [Cornutum/tcases#147]
I have a use cases that has hundreds of variables, and nearly all of them have properties with multiple conditions.  This runs fine with tuple coverage of 1, however if increase it to 2 the performance is extremely slow.

I started a calculation on Saturday, it's now three days later, and I can see from the log file it is producing a new test every 1.5-3 hours.

Is there any options to spread across multiple cores, or otherwise optimise?

Thanks in advance!

**Comment by kerrykimbrough** [comment]
If your system input model contains several functions, try splitting into several models of one function each.

This works because test cases for each function are generated independently. So it would be possible to improve performance for such models by running function test case generation in parallel. That's certainly an idea worth pursuing.

Also, there is a reason why 2-way coverage can be much more expensive than 1-way coverage. This can happen when there are a lot of conditions on feasible combinations. In this case, there can be many 2-tuples that are infeasible. But in some cases, an infeasible tuple can be detected only by an exhaustive search of all possible combinations. That can take a really long time, especially if there are lots of variables. In this situation, you might be able to avoid infeasible combinations by being more selective about exactly which variables get 2-way combination. For example, given variables A, B, C, D, instead of 2-tuples for all 4, you might find that smaller combination groups -- say, (A,B) and (C,D) -- provide sufficient coverage.

**Comment by kerrykimbrough** [comment]
At any rate, your model presents a very interesting situation. If you are willing to contribute this as a test case, I will give it more study.

**Comment by AdamLeonSmith** [comment]
Thanks for your thoughts.  It is still progressing and finding test cases.  It is a single function with a large number of inputs, so I don't think I can break it down.

I will attempt what you have suggested - applying 2 tuple coverage on say sets of 10 variables at a time - in order to see if there is actually some infeasible combinations in there.  At least, that may give me insight.

I'm not sure I can contribute it as a test case directly, but if when I do the above, it still points at an interesting performance issue - I could probably desensitise it.

**Comment by kerrykimbrough** [comment]
For example, consider combination group (A, B, C). Suppose we know that B and C are mutually independent. Then you get the same effective coverage with groups (A,B) and (A,C).

**Comment by kerrykimbrough** [comment]
The tcases.log file should warn you about every infeasible 2-tuple that was ignored.

**Comment by disc0tech** [comment]
This is still running :)  I've tried running smaller subsets to detect any issues or infeasible combos and haven't found any.

Is it possible to exclude failure test cases?  This might help quite a lot.

**Comment by kerrykimbrough** [comment]
I'd be very surprised if this long-running job has even started producing failure cases yet. I don't think excluding failures will speed things up, because at that stage test cases are assembled with 1-tuples. According to previous comments, that process went reasonably quickly.

**Comment by kerrykimbrough** [comment]
Also, I'd be very surprised if you have encountered no infeasible 2-tuples. Look in the tcases.log file. Infeasible tuples are indicated by WARN messages like this:

```
13:05:51.098 WARN  o.c.t.generator.TupleGenerator - Can't create test case for tuple=Tuple[[blanks=one, quoted=no]]
```

**Comment by kerrykimbrough** [comment]
When you're experimenting with smaller slices of the input model, be sure to check first using basic 1-tuple coverage. That will help to expose any constraint problems that might be accidentally introduced.

**Comment by kerrykimbrough** [comment]
You might try running with log level TRACE (at the shell command line, `-L TRACE`). That will produce a ton of log messages but it will show every step of the search for values to complete a test case for each tuple. That can help you understand why the search is taking so long.

**Comment by disc0tech** [comment]
Hi - thanks for your help.  I ended up using python to build a graph to figure out the actual dependencies between fields, then programatically subdividing vars into groups.  Then  I identified some infeasible combinations, and now it runs in less than a minute.

**Comment by kerrykimbrough** [comment]
Well done!
