### ISSUE TITLE
Better if Tcases can validate the response json schema in the api spec

### ISSUE THREAD

**Issue by rkariyawas** [Cornutum/tcases#164]
In my api spec, it has the json response schema, So Tcases generates the test cases to validate request only.
So is it possible to add json response schema validation too (If the spec contains the response schema)

**Comment by kerrykimbrough** [comment]
The answer may depend on what you mean by "validate".

Do the generated test cases "validate" requests? If you mean "validate that request messages conform to the OpenAPI definition", the answer is "no". That's not necessary because the generation process ensures that request inputs conform.

If you mean "validate that requests return the expected responses", the answer is "partly". The generated tests do assert the expected type of response (i.e. success or failure), although this is based only on standard status code ranges (which might not be entirely accurate for your API). But these tests cannot automatically verify that the response contains the expected content. Tcases has no way to know what values your API is expected to return for any request. You have to add that verification code yourself.

If you mean "validate that the _form_ of the response message conforms to the OpenAPI definition", that is not impossible. But that is not really a job for Tcases. There are many different packages you could use to do that. For example: https://bitbucket.org/atlassian/swagger-request-validator/src/master/. Also, the way you handle that will probably depend on how you decide to verify response content.

**Comment by rkariyawas** [comment]
What I thought is apped schema validation like below (JsonSchemaFile should be generated using API spec):

.assertThat()
            .body(matchesJsonSchemaInClasspath("JsonSchemaFile.json"));
            
Thanks for your thoughts.

**Comment by kerrykimbrough** [comment]
You can do that using the `swagger-request-validator` mentioned previously. Look at the examples for the restassured adapter: https://bitbucket.org/atlassian/swagger-request-validator/src/master/swagger-request-validator-examples/src/test/java/com/atlassian/oai/validator/examples/restassured/OpenApiValidationFilterTestExample.java?at=master (Because you are testing a real API server, you can ignore the WireMock code for the mock server.)

**Comment by rkariyawas** [comment]
Yes this is for real server and thanks,
And I will check that

**Comment by kerrykimbrough** [comment]
No change planned for this issue

**Comment by kerrykimbrough** [comment]
Hi, @rkariyawas 

In case you did not notice already, the [latest release](https://github.com/Cornutum/tcases/blob/master/ReleaseNotes.md#380) includes a fix for this issue. I guess my previous comment was too hasty!

**Comment by kerrykimbrough** [comment]
Fixed by PR #221
