### ISSUE TITLE
Potential minor refactor of `org.cornutum.tcases.io.AbstractFilter.getSource()` for readability

### ISSUE THREAD

**Issue by lintong** [Cornutum/tcases#92]
Hi @kerrykimbrough 

Do you think it's worth refactoring `org.cornutum.tcases.io.AbstractFilter.getSource()` to be called `getDestination()`? This method call retrieves a reference to an OutputStream that is the result of a transformation.  

Many thanks

**Comment by kerrykimbrough** [comment]
Actually, the `getSource` stream is the **input** to the filter. That's why, from the filter's POV, it is described as the "source". 

You can think of an `AbstractFilter` as a component of a data processing pipeline. In other words, data written to this stream is unfiltered original information. An `AbstractFilter` is then responsible for writing the transformed form to the `getTarget` stream.

**Comment by lintong** [comment]
I think it's slightly weird to see `TcasesIO.writeTests(Tcases.getTests(inputDef, null, null), transformer.getSource() /*where Source is actually the OutputStream*/);`

I'm happy for you to keep it as is though.
